### PR TITLE
Initialize FileSystem during pre-generation

### LINKED ISSUE #145: file_get_contents() on null in /usr/local/www/nextcloud/lib/private/Files/Filesystem.php:710
Hi,

after uploading thousands of JPGs I get these quite a bit:

`An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /usr/local/www/nextcloud/lib/private/Files/Filesystem.php:710
Stack trace:
#0 /usr/local/www/nextcloud/lib/private/legacy/image.php(622): OC\Files\Filesystem::file_get_contents('/data/nextcloud...')
#1 /usr/local/www/nextcloud/lib/private/Preview/Image.php(57): OC_Image->loadFromFile('/data/nextcloud...')
#2 /usr/local/www/nextcloud/lib/private/Preview/GeneratorHelper.php(59): OC\Preview\Image->getThumbnail('P1000740.JPG', 4096, 4096, false, Object(OC\Files\View))
#3 /usr/local/www/nextcloud/lib/private/Preview/Generator.php(194): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\JPEG), Object(OC\Files\Node\File), 4096, 4096)
#4 /usr/local/www/nextcloud/lib/private/Preview/Generator.php(118): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/jpeg')
#5 /usr/local/www/nextcloud/lib/private/PreviewManager.php(205): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'image/jpeg')
#6 /usr/local/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(205): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#7 /usr/local/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(193): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#8 /usr/local/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(164): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#9 /usr/local/www/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(132): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#10 /usr/local/www/nextcloud/3rdparty/symfony/console/Command/Command.php(251): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /usr/local/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /usr/local/www/nextcloud/console.php(96): OC\Console\Application->run()
#16 /usr/local/www/nextcloud/occ(11): require_once('/usr/local/www/...')
#17 {main}`

Any idea what could be causing this and how to fix it?

Regards,
   JP

### PR DESCRIPTION
**Pull request by apmole**
Fixes #145, at least for my setup. I do not know if that is the proper way to initialize the static FileSystem object.

### CODE REVIEW

**Comment by ChrisHaPunkt** [comment]
Can we have this build re-triggered?

**Comment by MichaIng** [comment]
The builds are currently doomed to fail since they run PHP version which are not compatible with latest Nextcloud anymore. This is what needs to be done first: https://github.com/rullzer/previewgenerator/pull/190/commits/bd022b0146f5eec66921d6c6eb47720ed8a1abc2

**Comment by Flova** [comment]
This fixes the error for me.

**Comment by MichaIng** [comment]
@apmole 
Could you rebase your commit onto the current master, so that the new GitHub action based checks can run through?

**Comment by apmole** [comment]
@MichaIng done

**Comment by MichaIng** [comment]
Strict coding standards 😄. The indentation should be two real tabs instead of white spaces, like in the other cases.

**Comment by apmole** [comment]
@MichaIng fixed indentation

**Review by MichaIng — APPROVED** [review]

**Comment by MichaIng** [comment]
My approval does not count here, but this fixes a replicable error that is reported by a large number of users across at least 4 issues (not all open anymore) and at least I couldn't find any feedback that this fix caused any other issues.

I don't know if there is a better way either, but a working and already often manually applied fix is better than leaving it as it is, IMO 😃.

@rullzer kindly pinging you here as, compared to the other PRs this fixes an actual bug users run into, so probably worth to give it some priority.

**Pull request merged**
