### PR TITLE
Add timestamps to verbose process messages

### PR DESCRIPTION
**Pull request by MichaIng**
- Makes it easier to find files for related errors e.g. on nextcloud log.
- Derive duration for generating previews, performance testing etc.
- MySQL DATETIME format is used to have some kind of standard.
- Maybe there is an easier way to provide a timestamp for every php execution message, perhaps even in local time and date format?

### CODE REVIEW

**Comment by MichaIng** [comment]
I just recognized that on my server UTC is used by `date()` instead of local server time zone. Everything I can find out about that says, that `local` time will be used by default. On other logs and SSH client I see time/date given as `+2` (MEST), just the preview generation with my commits provide UTC 😞 .

Is this the same result for you or perhaps well known? In case how to easily assure that local time zone will be used?

**Comment by MichaIng** [comment]
Is this not wanted? I still found this to be very helpful for every testing/debugging purpose and manually (have to) add it after every update.

**Comment by rullzer** [comment]
Sorry for the late reply

Regarding the timestamps. The server code defaults to UTC.

**Comment by rullzer** [comment]
Mmm so there actually is already function in the server that would do just this https://github.com/nextcloud/server/blob/master/lib/private/Console/TimestampFormatter.php even with the timezone magic etc.

Lets see if i can hijack that ;)

**Comment by MichaIng** [comment]
Close in favour of: https://github.com/rullzer/previewgenerator/pull/88

**Pull request closed without merging**
